title: JJy Blog
description: "A place to put some random thoughts"
author:
  name: "JJy"
  email: "jjyruby@gmail.com"
  url: "https://justjjy.com"
site:
  url: "https://justjjy.com"

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "JJy"
year : "2019"
