baseURL = "https://jjylab.com/"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false
title = "JJy"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]

[permalinks]
posts = "/posts/:slugorcontentbasename/"

[languages]
  [languages.zh]
    locale = "zh-CN"
    label = "中文"
    contentDir = "content"
    weight = 1
    title = "JJy"

  [languages.en]
    locale = "en"
    label = "English"
    contentDir = "content"
    weight = 2
    title = "JJy"

[params]
name = "JJy"
github = "https://github.com/jjyr"
x = "https://x.com/jjybtw"
email = "jjyruby@gmail.com"
