baseURL = "https://jjylab.com/"
locale = "zh-CN"
defaultContentLanguage = "zh-cn"
title = "JJy"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]

[permalinks]
posts = "/posts/:slugorcontentbasename/"

[params]
name = "JJy"
github = "https://github.com/jjyr"
x = "https://x.com/jjybtw"
email = "jjyruby@gmail.com"
